### ISSUE TITLE
Problem with compilation - missing library inet.h

### ISSUE THREAD

**Issue by JarekParal** [RoboticsBrno/mickoflus-demo01#1]
https://travis-ci.org/RoboticsBrno/mickoflus-demo01/builds/477481910#L553

Could you check that please @Tasssadar?

**Comment by JarekParal** [comment]
Do you know where could be problem @Tasssadar?

**Comment by Tasssadar** [comment]
https://github.com/RoboticsBrno/RB3201-RBProtocol-library/commit/113467749efcd5d9cbae71f160d8f8d44f0bf4bc but couldn't update this repo because the library wasn't updated in platformio registry yet.
